import '@/styles/globals.css'
import { Inter, MonteCarlo } from 'next/font/google'

const inter = Inter({ 
  subsets: ['latin'],
  variable: '--font-inter',
})
const montecarlo = MonteCarlo({ 
  subsets: ['latin'], 
  weight: '400',
  variable: '--font-mont'
})

export const metadata = {
  title: 'Portfolio Project',
  description: 'Generated by a human',
  viewport: {
    width: 'device-width',
    initialScale: 1,
    maximumScale: 1,
  },
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.variable}`}>{children}</body>
    </html>
  )
}
